# LAB Text Generation with Neural Networks

## Functions for Processing Text

### Reading in files as a string text

In [3]:
def read_file(filepath):
    
    with open(filepath) as f:
        str_text = f.read()
    
    return str_text

#### Call the function below and read teh file: moby_dick_four_chapters.txt

In [10]:
file_path = 'moby_dick_four_chapters.txt'  # make sure this path is correct
text = read_file(file_path)


'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

#### import spacy

In [13]:
import spacy

#### load: en_core_web_sm and assign it to a variable call "nlp"

In [15]:
nlp = spacy.load("en_core_web_sm")

#### Let's calculate the length

In [23]:
nlp.max_length = 1198623

#### create a function to separate punctuation

In [26]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [28]:
#### call the function read_file and read the file: melville-moby_dick.txt and save it in a variable called "d"

In [30]:
file_path = 'C:\\Users\\William\\Desktop\\Week 9 Lab - Text with LSTM\\melville-moby_dick.txt'
d = read_file(file_path)

In [ ]:
#### using a variable called tokens, call the separate_punc function. Send "d" as a parameter

In [32]:
tokens = separate_punc(d)

#### List the tokens

In [35]:
print(tokens)


['chapter', '1', 'loomings', 'call', 'me', 'ishmael', 'some', 'years', 'ago', 'never', 'mind', 'how', 'long', 'precisely', 'having', 'little', 'or', 'no', 'money', 'in', 'my', 'purse', 'and', 'nothing', 'particular', 'to', 'interest', 'me', 'on', 'shore', 'i', 'thought', 'i', 'would', 'sail', 'about', 'a', 'little', 'and', 'see', 'the', 'watery', 'part', 'of', 'the', 'world', 'it', 'is', 'a', 'way', 'i', 'have', 'of', 'driving', 'off', 'the', 'spleen', 'and', 'regulating', 'the', 'circulation', 'whenever', 'i', 'find', 'myself', 'growing', 'grim', 'about', 'the', 'mouth', 'whenever', 'it', 'is', 'a', 'damp', 'drizzly', 'november', 'in', 'my', 'soul', 'whenever', 'i', 'find', 'myself', 'involuntarily', 'pausing', 'before', 'coffin', 'warehouses', 'and', 'bringing', 'up', 'the', 'rear', 'of', 'every', 'funeral', 'i', 'meet', 'and', 'especially', 'whenever', 'my', 'hypos', 'get', 'such', 'an', 'upper', 'hand', 'of', 'me', 'that', 'it', 'requires', 'a', 'strong', 'moral', 'principle', 'to'

#### Get the lenght of tokens

In [43]:
tokens_length = len(tokens)

print("Number of tokens:", tokens_length)


result = 4431 / 25
print("4431 / 25 =", result)


Number of tokens: 214708
4431 / 25 = 177.24


In [9]:
4431/25

177.24

## Create Sequences of Tokens

In [46]:
# organize into sequences of tokens
train_len = 25+1 # 50 training words , then one target word

# Empty list of sequences
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

#### using ' '.join() display the words of the first sequence [0]

In [49]:
' '.join(text_sequences[0])

'chapter 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to'

#### display the words of the second sequence [1]

In [57]:
print("Second sequence:", ' '.join(text_sequences[1]))


Second sequence: 1 loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest


#### display the words of the third one

In [60]:
print("Third sequence:", ' '.join(text_sequences[2]))


Third sequence: loomings call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me


#### get the length of text_sequences

In [63]:
text_sequences_length = len(text_sequences)
print("Number of sequences:", text_sequences_length)


Number of sequences: 214682


# Keras

### Keras Tokenization

#### import Tokenizer from Keras...

In [95]:
from tensorflow.keras.preprocessing.text import Tokenizer

# Create a Tokenizer instance
tokenizer = Tokenizer()

# Fit the tokenizer on the tokens
tokenizer.fit_on_texts(tokens)


In [97]:
# integer encode sequences of words
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

#### List the sequences[0]

In [100]:
print("First sequence:", sequences[0])


First sequence: [158, 9443, 17526, 402, 42, 1043, 43, 247, 659, 140, 296, 116, 82, 787, 347, 113, 36, 50, 1788, 6, 49, 3028, 3, 218, 442, 5]


#### display the tokenizer.index_word

In [102]:
print("Tokenizer index_word:", tokenizer.index_word)


Tokenizer index_word: {1: 'the', 2: 'of', 3: 'and', 4: 'a', 5: 'to', 6: 'in', 7: 'that', 8: 'his', 9: 'it', 10: 'i', 11: 'he', 12: 'but', 13: "'s", 14: 'as', 15: 'with', 16: 'is', 17: 'was', 18: 'for', 19: 'all', 20: 'this', 21: 'at', 22: 'not', 23: 'by', 24: 'whale', 25: 'from', 26: 'so', 27: 'him', 28: 'on', 29: 'be', 30: 'one', 31: 'you', 32: 'there', 33: 'now', 34: 'had', 35: 'have', 36: 'or', 37: 'were', 38: 'they', 39: 'like', 40: 'which', 41: 'then', 42: 'me', 43: 'some', 44: 'their', 45: 'what', 46: 'when', 47: 'an', 48: 'are', 49: 'my', 50: 'no', 51: 'upon', 52: 'out', 53: 'man', 54: 'into', 55: 'ship', 56: 'up', 57: 'more', 58: 'ahab', 59: 'if', 60: 'them', 61: 'old', 62: 'we', 63: 'sea', 64: 'would', 65: "'", 66: 'ye', 67: 'do', 68: 'other', 69: 'been', 70: 'over', 71: 'these', 72: 'will', 73: 'though', 74: 'only', 75: 'its', 76: 'down', 77: 'such', 78: 'who', 79: 'yet', 80: 'head', 81: 'time', 82: 'long', 83: 'boat', 84: 'her', 85: 'any', 86: 'captain', 87: 'very', 88: 'her

{1: 'the',
 2: 'of',
 3: 'and',
 4: 'a',
 5: 'to',
 6: 'in',
 7: 'that',
 8: 'his',
 9: 'it',
 10: 'i',
 11: 'he',
 12: 'but',
 13: "'s",
 14: 'as',
 15: 'with',
 16: 'is',
 17: 'was',
 18: 'for',
 19: 'all',
 20: 'this',
 21: 'at',
 22: 'not',
 23: 'by',
 24: 'whale',
 25: 'from',
 26: 'so',
 27: 'him',
 28: 'on',
 29: 'be',
 30: 'one',
 31: 'you',
 32: 'there',
 33: 'now',
 34: 'had',
 35: 'have',
 36: 'or',
 37: 'were',
 38: 'they',
 39: 'like',
 40: 'which',
 41: 'then',
 42: 'me',
 43: 'some',
 44: 'their',
 45: 'what',
 46: 'when',
 47: 'an',
 48: 'are',
 49: 'my',
 50: 'no',
 51: 'upon',
 52: 'out',
 53: 'man',
 54: 'into',
 55: 'ship',
 56: 'up',
 57: 'more',
 58: 'ahab',
 59: 'if',
 60: 'them',
 61: 'old',
 62: 'we',
 63: 'sea',
 64: 'would',
 65: "'",
 66: 'ye',
 67: 'do',
 68: 'other',
 69: 'been',
 70: 'over',
 71: 'these',
 72: 'will',
 73: 'though',
 74: 'only',
 75: 'its',
 76: 'down',
 77: 'such',
 78: 'who',
 79: 'yet',
 80: 'head',
 81: 'time',
 82: 'long',
 83: 'boat

#### using a for loop, for i in sequences[0], print the tokenizer.index_word

In [105]:
for i in sequences[0]:
    print(f"Index {i}: {tokenizer.index_word[i]}")


Index 158: chapter
Index 9443: 1
Index 17526: loomings
Index 402: call
Index 42: me
Index 1043: ishmael
Index 43: some
Index 247: years
Index 659: ago
Index 140: never
Index 296: mind
Index 116: how
Index 82: long
Index 787: precisely
Index 347: having
Index 113: little
Index 36: or
Index 50: no
Index 1788: money
Index 6: in
Index 49: my
Index 3028: purse
Index 3: and
Index 218: nothing
Index 442: particular
Index 5: to


158 : chapter
9443 : 1
17526 : loomings
402 : call
42 : me
1043 : ishmael
43 : some
247 : years
659 : ago
140 : never
296 : mind
116 : how
82 : long
787 : precisely
347 : having
113 : little
36 : or
50 : no
1788 : money
6 : in
49 : my
3028 : purse
3 : and
218 : nothing
442 : particular
5 : to


#### print the tokenizer.word_counts

In [108]:
print("Word counts:", tokenizer.word_counts)


Word counts: OrderedDict([('chapter', 4447), ('1', 28), ('loomings', 3), ('call', 1382), ('me', 16095), ('ishmael', 500), ('some', 15789), ('years', 2400), ('ago', 815), ('never', 5262), ('mind', 2039), ('how', 6330), ('long', 8567), ('precisely', 690), ('having', 1679), ('little', 6412), ('or', 17879), ('no', 14916), ('money', 305), ('in', 105799), ('my', 15231), ('purse', 178), ('and', 164029), ('nothing', 2936), ('particular', 1273), ('to', 117832), ('interest', 442), ('on', 26910), ('shore', 572), ('i', 53430), ('thought', 3874), ('would', 11232), ('sail', 2522), ('about', 7982), ('a', 119756), ('see', 6734), ('the', 367474), ('watery', 650), ('part', 3874), ('of', 168116), ('world', 4420), ('it', 64056), ('is', 43758), ('way', 6942), ('have', 19604), ('driving', 234), ('off', 5642), ('spleen', 26), ('regulating', 26), ('circulation', 26), ('whenever', 390), ('find', 1404), ('myself', 1716), ('growing', 234), ('grim', 286), ('mouth', 1456), ('damp', 234), ('drizzly', 26), ('novembe

OrderedDict([('chapter', 4447),
             ('1', 28),
             ('loomings', 3),
             ('call', 1382),
             ('me', 16095),
             ('ishmael', 500),
             ('some', 15789),
             ('years', 2400),
             ('ago', 815),
             ('never', 5262),
             ('mind', 2039),
             ('how', 6330),
             ('long', 8567),
             ('precisely', 690),
             ('having', 1679),
             ('little', 6412),
             ('or', 17879),
             ('no', 14916),
             ('money', 305),
             ('in', 105799),
             ('my', 15231),
             ('purse', 178),
             ('and', 164029),
             ('nothing', 2936),
             ('particular', 1273),
             ('to', 117832),
             ('interest', 442),
             ('on', 26910),
             ('shore', 572),
             ('i', 53430),
             ('thought', 3874),
             ('would', 11232),
             ('sail', 2522),
             ('about', 

#### get the len of tokenizer.word_counts and assign it to a variable called vocabulary_size

In [111]:
vocabulary_size = len(tokenizer.word_counts)

print("Vocabulary size:", vocabulary_size)


Vocabulary size: 17526


### Convert to Numpy Matrix

In [114]:
import numpy as np

#### Create a numpy array with the seqences and call it sequences

In [122]:
sequences_array = np.array(sequences)

print("Numpy array shape:", sequences_array.shape)


Numpy array shape: (214682, 26)


#### print the sequences

In [124]:
print("Sequences array:\n", sequences_array)


Sequences array:
 [[  158  9443 17526 ...   218   442     5]
 [ 9443 17526   402 ...   442     5  1165]
 [17526   402    42 ...     5  1165    42]
 ...
 [  240   938   351 ...  1419  1313    74]
 [  938   351  1418 ...  1313    74   219]
 [  351  1418     3 ...    74   219   222]]


array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

# Creating an LSTM based model

#### import keras, Sequential, Dense, LSTM, and Embedding

In [126]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding


#### def a function called:  create_model(vocabulary_size, seq_len): <br> in the model add a sequential model, add (Embedding(vocabulary_size, 25, input_length=seq_len), add (LSTM(150, return_sequences=True), add (LSTM(150), add (Dense(150, activation='relu'), Dense(vocabulary_size, activation='softmax')<br> then compile the model using; loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'] <br> finally, print the summary of the model and return the model. 

In [132]:
from keras.models import Sequential
from keras.layers import Dense, LSTM, Embedding

def create_model(vocabulary_size, seq_len):
    
    model = Sequential()
    
    
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))  
    model.add(LSTM(150, return_sequences=True))  
    model.add(LSTM(150))  
    model.add(Dense(150, activation='relu'))  
    model.add(Dense(vocabulary_size, activation='softmax'))  

    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

    
    model.summary()

    return model


### Train / Test Split

#### import to_categorical from from tensorflow.keras.utils 

In [134]:
from tensorflow.keras.utils import to_categorical


#### display the sequences

In [139]:
print("Sequences array:\n", sequences_array)


Sequences array:
 [[  158  9443 17526 ...   218   442     5]
 [ 9443 17526   402 ...   442     5  1165]
 [17526   402    42 ...     5  1165    42]
 ...
 [  240   938   351 ...  1419  1313    74]
 [  938   351  1418 ...  1313    74   219]
 [  351  1418     3 ...    74   219   222]]


array([[  158,  9443, 17526, ...,   218,   442,     5],
       [ 9443, 17526,   402, ...,   442,     5,  1165],
       [17526,   402,    42, ...,     5,  1165,    42],
       ...,
       [  240,   938,   351, ...,  1419,  1313,    74],
       [  938,   351,  1418, ...,  1313,    74,   219],
       [  351,  1418,     3, ...,    74,   219,   222]])

#### now, display the first 49 

In [150]:
first_49_sequences = sequences_array[:49, :-1]
print("First 49 sequences (excluding last token):\n", first_49_sequences)


First 49 sequences (excluding last token):
 [[  158  9443 17526 ...     3   218   442]
 [ 9443 17526   402 ...   218   442     5]
 [17526   402    42 ...   442     5  1165]
 ...
 [    9    16     4 ...     1   381  1314]
 [   16     4   104 ...   381  1314     9]
 [    4   104    10 ...  1314     9    16]]


#### now display the last word only

In [152]:
last_words = sequences_array[:, -1]
print("Last words of each sequence:\n", last_words)


Last words of each sequence:
 [   5 1165   42 ...   74  219  222]


#### assing the sequences to the variables X, and y

In [169]:
X = sequences_array[:, :-1]


In [171]:
y = sequences_array[:, -1]


In [173]:
y = to_categorical(y, num_classes=vocabulary_size)


In [174]:
seq_len = X.shape[1]


In [177]:
print("Length of sequences (seq_len):", seq_len)


Length of sequences (seq_len): 25


### Training the Model

#### define the model 

In [188]:
model = create_model(vocabulary_size + 1, seq_len)


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

---

----

#### import dump,load from pickle 

In [193]:
from pickle import dump, load


In [199]:
#### fit the model using X, y, batch_size=128, epochs=5,verbose=1

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.utils import to_categorical

def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, 25, input_length=seq_len))
    model.add(LSTM(150, return_sequences=True))
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))
    model.add(Dense(vocabulary_size, activation='softmax'))

    # Compile the model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    # Print model summary
    model.summary()
    
    return model

# Create the model
model = create_model(vocabulary_size + 1, seq_len)

from tensorflow.keras import backend as K

K.clear_session()

# Fit the model again
history = model.fit(X, y, batch_size=128, epochs=5, verbose=1)


print("Shape of X:", X.shape)  # Should be (num_samples, seq_len)
print("Shape of y:", y.shape)  # Should be (num_samples, num_classes)



Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_8 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_9 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)


Epoch 1/5
1678/1678 ━━━━━━━━━━━━━━━━━━━━ 96s 55ms/step - accuracy: 0.0663 - loss: 7.1950
Epoch 2/5
1678/1678 ━━━━━━━━━━━━━━━━━━━━ 95s 56ms/step - accuracy: 0.0818 - loss: 6.5881
Epoch 3/5
1678/1678 ━━━━━━━━━━━━━━━━━━━━ 96s 57ms/step - accuracy: 0.0884 - loss: 6.3925
Epoch 4/5
1678/1678 ━━━━━━━━━━━━━━━━━━━━ 98s 58ms/step - accuracy: 0.0991 - loss: 6.2141
Epoch 5/5
1678/1678 ━━━━━━━━━━━━━━━━━━━━ 96s 57ms/step - accuracy: 0.1093 - loss: 6.0703
Shape of X: (214682, 25)
Shape of y: (214682, 17527)


#### save the model to file and call it: newtext.h5

In [203]:
model.save('newtext.h5')


#### save the tokenizer

In [205]:
from pickle import dump


with open('newtext.pkl', 'wb') as file:
    dump(tokenizer, file)


# Generating New Text

#### import: randint from random, load from pickle,  load_model from keras.models and pad_sequences

In [212]:
from random import randint
from pickle import load
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing.sequence import pad_sequences


#### run this function below

In [215]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate (50 words in the video)
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict Class Probabilities for each word - Original
        #pred_word_ind = model.predict_classes(pad_encoded, verbose=0)[0]
        
        #good one so far: 
        pred_word_ind = (model.predict(pad_encoded) > 0.5).astype("int32")
        
        #pred_word_ind = (model.predict(pad_encoded)).astype("int32")
        #pred_word_ind = (model.predict(pad_encoded) > 0.5)
        
        # Grab word
        #pred_word = tokenizer.index_word[pred_word_ind] 
        pred_word = (tokenizer.index_word[pred_word_ind])
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

### Grab a random seed sequence. For instance text_sequences[0]

In [217]:
import random

# Grab a random seed sequence from text_sequences
random_index = random.randint(0, len(text_sequences) - 1)  # Get a random index
seed_sequence = text_sequences[random_index]  # Get the sequence

# Convert the sequence back to a string format
seed_text = ' '.join(seed_sequence)  # Join tokens into a single string

print("Random Seed Sequence:")
print(seed_text)


Random Seed Sequence:
horn to see any more of it eh ca n't ye see the world where you stand i was a little staggered but go a whaling


In [219]:
import random
random.seed(101)
random_pick = random.randint(0,len(text_sequences))

In [221]:
random_seed_text = text_sequences[random_pick]

In [45]:
random_seed_text

['he',
 'recognised',
 'his',
 'cutting',
 'spade',
 'pole',
 'entangled',
 'in',
 'the',
 'lines',
 'that',
 'were',
 'knotted',
 'round',
 'the',
 'tail',
 'of',
 'one',
 'of',
 'these',
 'whales',
 'there',
 "'s",
 'a',
 'pretty',
 'fellow']

In [223]:
seed_text = ' '.join(random_seed_text)

In [47]:
seed_text

"he recognised his cutting spade pole entangled in the lines that were knotted round the tail of one of these whales there 's a pretty fellow"

### Exploring Generated Sequence

#### create a variable called full_text and read the file: moby_dick_four_chapters.txt

In [225]:
# Specify the file path
file_path = r'C:\Users\William\Desktop\Week 9 Lab - Text with LSTM\moby_dick_four_chapters.txt'

# Read the full text
full_text = read_file(file_path)

In [49]:
for i,word in enumerate(full_text.split()):
    if word == 'inkling':
        print(' '.join(full_text.split()[i-20:i+20]))
        print('\n')

were stains of some sort or other. At first I knew not what to make of this; but soon an inkling of the truth occurred to me. I remembered a story of a white man--a whaleman too--who, falling among the




#### That's the end